### ISSUE TITLE
no effect use 'table-success' in 'table-striped' darker strip rows

### ISSUE THREAD

**Issue by ccfontes** [rakuten-frontend/rex-css-framework#26]
Using a `<table>`'s `<tr class='table-success'>` has no effect on a gray strip arrow of a `<table class='table-striped'>`. I would expect to see a `'table-success'` green instead, in mentioned `<tr>`.

**Comment by claudio-moya** [comment]
Merged into https://github.com/rakuten-frontend/rex-css-framework/releases/tag/v0.1.4-beta

Thanks!
