### ISSUE TITLE
docs typo

### ISSUE THREAD

**Issue by ccfontes** [rakuten-frontend/rex-css-framework#27]
In the documentation, `.contaner` probably refers to `.container`.

**Comment by JohnoverBoard** [comment]
Hey, I can help by submitting a PR if you could specify the location where the typo error is.

**Comment by ccfontes** [comment]
Sure, thanks. Please see below.

In github: https://github.com/rakuten-frontend/rex-css-framework/search?q=contaner&unscoped_q=contaner

In the [online docs](https://rakuten-frontend.github.io/rex-css-framework/), searching for **.contaner** will yield two occurrences.

**Comment by JohnoverBoard** [comment]
#30

**Comment by claudio-moya** [comment]
Merged into https://github.com/rakuten-frontend/rex-css-framework/releases/tag/v0.1.4-beta

Thanks!
